TwoWheelsWeb/ViewModels/ForumViewModels.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

using TwoWheelsWeb.Models.ForumModels;

namespace TwoWheelsWeb.ViewModels
{
    public class ForumViewModels
    {
        public class ForumMainPageViewModel
        {
            public List<CategoryWithSubcategories> List { get; set; }
        }

        public class CategoryWithSubcategories
        {
            public Category Category { get; set; }
            public List<SubCategory> SubCategories { get; set; }
        }

        public class CategoryTopicsViewModel
        {
            public List<Topic> Topics { get; set; }
            public List<SubCategory> SubCategories { get; set; }
            public string CategoryId { get; set; }
            public string CategoryName { get; set; }
        }

        public class CreateTopicViewModel
        {
            public string CategoryId { get; set; }
            public Topic Topic { get; set; }
            [AllowHtml]
            public string PostContent { get; set; }
            public string Tags { get; set; }
        }

        public class TopicContentViewModel
        {
            public string Username { get; set; }
            public Topic Topic { get; set; }
            public List<PostWithAuthor> Posts { get; set; }
        }

        public class PostWithAuthor
        {
            public Post Post { get; set; }
            public string Username { get; set; }
        }

        public class CreatePostViewModel
        {
            public Post Post { get; set; }
            public string TopicId { get; set; }
        }

        public class SearchedTopicsViewModel
        {
            public string SearchedTag { get; set; }
            public List<Topic> Topics { get; set; }
        }

        public class CreateCategoryViewModel
        {
            public Category Category { get; set; }
            public string Id { get; set; }
        }
    }
}

TwoWheelsWeb/Controllers/ForumController.cs
using System.Threading.Tasks;
using System.Web.Mvc;

using TwoWheelsWeb.Models.ForumModels;
using TwoWheelsWeb.Services;

using static TwoWheelsWeb.ViewModels.ForumViewModels;

namespace TwoWheelsWeb.Controllers
{
    public class ForumController : Controller
    {
        private readonly ForumService _forumService;

        public ForumController()
        {
            this._forumService = new ForumService();
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var model = await _forumService.GetForumMainPageViewModel();

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> GetCategoryTopics(string id)
        {
            var topicsModel = await _forumService.GetCategoryTopics(id);

            return View(topicsModel);
        }

        [HttpGet]
        public async Task<ActionResult> GetTopic(string id)
        {
            var content = await this._forumService.GetTopicContent(id);

            return this.View(content);
        }

        [HttpGet]
        public ActionResult CreateTopic(string id)
        {
            var model = this._forumService.GetCreateTopicViewModel(id);

            return this.View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CreateTopic(CreateTopicViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var response = await this._forumService.CreateTopic(model);

            return !response.Equals(string.Empty)
                ? this.RedirectToAction("GetTopic", new { id = response.Trim('"') })
                : this.RedirectToAction("CreateTopic", new { id = model.CategoryId });
        }

        [HttpGet]
        public ActionResult CreatePost(string id)
        {
            var model = this._forumService.GetCreatePostViewModel(id);
            
            return this.View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CreatePost(CreatePostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var isCreated = await this._forumService.CreatePost(model);

            return isCreated ? RedirectToAction("GetTopic", new { id = model.TopicId }) : RedirectToAction("CreatePost", new {id=model.TopicId});
        }

        [HttpGet]
        public ActionResult CreateCategory(string id = null)
        {
            var model = this._forumService.GetCreateCategoryViewModel(id);

            return this.View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CreateCategory(CreateCategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var result = await this._forumService.CreateCategory(model);

            return result ? RedirectToAction("Index") : this.RedirectToAction("CreateCategory");
        }

        [HttpGet]
        public async Task<ActionResult> SearchByTag(string tag)
        {
            var model = await this._forumService.SearchByTag(tag);

            return this.View(model);
        }
    }

}

TwoWheelsWeb/Views/Forum/CreateCategory.cshtml
@model TwoWheelsWeb.ViewModels.ForumViewModels.CreateCategoryViewModel

@{
    Page.Title = "Creating new category";
}

<div>
    @using (Html.BeginForm("CreateCategory", "Forum", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.Id)
        <div class="grid">
            <div class="row cells2">
                <div class="row">@Html.LabelFor(x => x.Category.Name)</div>
                <div class="row">@Html.EditorFor(x => x.Category.Name)</div>
            </div>
        </div>
        <button type="submit" class="button btn-warning">Create!</button>
    }
</div>

TwoWheelsWeb/Views/Forum/CreatePost.cshtml
@model TwoWheelsWeb.ViewModels.ForumViewModels.CreatePostViewModel

@using (Html.BeginForm("CreatePost", "Forum", FormMethod.Post))
{
    @Html.HiddenFor(x => x.TopicId)
    
    <div>@Html.TextAreaFor(x => x.Post.Content)</div>
    
    <button type="submit" class="button btn-warning">Create post!</button>
}

@section scripts{
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    
    <script type="text/javascript">
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "modern",
            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline," + 
                "strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|," +
                "styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|," +
                "search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|," +
                "link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|," +
                "forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|," +
                "sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|," +
                "styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|," +
                "visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

        // Example content CSS (should be your site CSS)
        // content_css: "css/example.css",
        });
    </script>
}

TwoWheelsWeb/Views/Forum/CreateTopic.cshtml
@model TwoWheelsWeb.ViewModels.ForumViewModels.CreateTopicViewModel

@{
    Page.Title = "Create new topic";
}

<div>
    <h3>Create new topic</h3>
    <hr />
    <br />
    @using (Html.BeginForm("CreateTopic", "Forum", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.CategoryId)

        <div class="grid">
            <div class="row cells2">
                <div class="cell">@Html.LabelFor(x => x.Topic.Name)</div>
                <div class="cell">@Html.EditorFor(x => x.Topic.Name)</div>
            </div>
            <div class="row cells2">
                <div class="cell">@Html.LabelFor(x => x.Topic.Description)</div>
                <div class="cell">@Html.EditorFor(x => x.Topic.Description)</div>
            </div>
            <div class="row cells2">
                <div class="cell">@Html.LabelFor(x => x.Tags)</div>
                <div class="cell">@Html.EditorFor(x => x.Tags)</div>
                <p>Specify tags with commas</p>
            </div>
            <div>@Html.TextAreaFor(x => x.PostContent)</div>
        </div>
        <button class="button btn-warning">Create topic!</button>
    }
</div>

@section scripts{
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>

    <script type="text/javascript">
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "modern",
            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline," +
                "strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|," +
                "styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|," +
                "search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|," +
                "link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|," +
                "forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|," +
                "sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|," +
                "styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|," +
                "visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

        // Example content CSS (should be your site CSS)
        // content_css: "css/example.css",
        });
    </script>
}

TwoWheelsWeb/Views/Forum/GetCategoryTopics.cshtml
@using TwoWheelsWeb.Models.ForumModels
@model TwoWheelsWeb.ViewModels.ForumViewModels.CategoryTopicsViewModel

@{
    Page.Title = "Topics";
}

<h3>Topics in @Model.CategoryName</h3>
<hr />
<br/>
<a href="@Url.Action("CreateTopic", "Forum", new {id=Model.CategoryId})" class="button btn-warning"><span class=""></span> Create new topic!</a>
<br/>
<div>
    <table class="table">
        <thead>
        <tr>
            <th>Posts number</th>
            <th>Topic</th>
            <th>Start date</th>
        </tr>
        </thead>
        <tbody>
        @if (Model.SubCategories != null && Model.SubCategories.Count > 0)
        {
            foreach (var subCategory in Model.SubCategories)
            {
                if (subCategory == null)
                {
                    continue;
                }
                <tr>
                    <td><b><a href="@Url.Action("GetCategoryTopics", new {id=subCategory.ObjectId})">@subCategory.Name</a></b></td>
                    <td>#</td>
                    <td>#</td>
                </tr>
            }
        }
        @if (Model.Topics == null || Model.Topics.Count == 0)
        {
            <tr>
                <td>#</td>
                <td>There is no topics here!</td>
                <td>#</td>
            </tr>
        }
        else
        {
            foreach (Topic topic in Model.Topics)
            {
                <tr>
                    <td>@topic.Posts.Count</td>
                    <td><a href="@Url.Action("GetTopic", new { id = topic.ObjectId })">@topic.Name</a></td>
                    <td>@topic.StartDate</td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

TwoWheelsWeb/Views/Forum/GetTopic.cshtml
@model TwoWheelsWeb.ViewModels.ForumViewModels.TopicContentViewModel

@{
    Page.Title = Model.Topic.Name;
}

<h2>@Model.Topic.Name</h2>
<hr>
<br/>

<div class="panel panel-default">
    <div class="panel-heading">Tags:</div>
    <div class="panel-body">
        @foreach (var topicTag in Model.Topic.Tags)
        {
            <a href="@Url.Action("SearchByTag", "Forum", new { tag= topicTag.Name })">@topicTag.Name </a>
        }
    </div>
</div>

<div class="grid">
    @foreach (var item in @Model.Posts)
    {
        <div class="row">
            <div class="col-md-9 col-md-push-3">@Html.Raw(item.Post.Content)</div>
            <div class="col-md-3 col-md-pull-9">@item.Username<br/>@item.Post.PostDate.ToShortDateString()</div>
        </div>
    }
</div>
<br/>

<div id="newPostForm"></div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $.ajax({
                type: "GET",
                url: "/Forum/CreatePost?id=" + '@Model.Topic.ObjectId',
                datatype: "html",
                success: function(data) {
                    $('#newPostForm').html(data);
                },
                error: function() {
                    alert("Something gone wrong!");
                }
            });
        });
    </script>
}

TwoWheelsWeb/Views/Forum/Index.cshtml
@using TwoWheelsWeb.ViewModels
@model ForumViewModels.ForumMainPageViewModel

@{
    Page.Title = "Forum";
}

<h3>Forum</h3>
<br/>

<a href="@Url.Action("CreateCategory", "Forum")" class="button btn-warning"><span class=""></span> Add category!</a>

<div>
    <table class="table">
        <thead>
        <tr>
            <th>Category</th>
        </tr>
        </thead>
        <tbody>
        @if (Model.List == null || Model.List.Count < 1)
        {
            <tr><td><div>@Html.Raw("There is nothing here!")</div></td></tr>
        }
        else
        {
            foreach (var item in Model.List)
            {
                <tr>
                    <td>
                        <b><a href="@Url.Action("GetCategoryTopics", new {id = item.Category.ObjectId})">@item.Category.Name</a></b>
                    </td>
                    <td>
                        <a href="@Url.Action("CreateCategory", "Forum", new {id=item.Category.ObjectId})" class="button btn-warning"><span class=""></span> Add subcategory!</a>
                    </td>
                </tr>
                if (item.Category.SubCategories != null && item.Category.SubCategories.Count > 0)
                {
                    foreach (var subCategory in item.SubCategories)
                    {
                        if (subCategory == null)
                        {
                            continue;
                        }
                        <tr>
                            <td>
                                <a href="@Url.Action("GetCategoryTopics", new {id=subCategory.ObjectId})">@subCategory.Name</a>
                            </td>
                        </tr>    
                    }
                }
            }
        }
        </tbody>
    </table>
</div>

TwoWheelsWeb/Views/Forum/SearchByTag.cshtml
@using TwoWheelsWeb.Models.ForumModels
@model TwoWheelsWeb.ViewModels.ForumViewModels.SearchedTopicsViewModel

@{
    Page.Title = "Topics connected with tag";
}

<div class="panel panel-default">
    <div class="panel-heading">Topics connected with @Model.SearchedTag tag:</div>
</div>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Posts number</th>
                <th>Topic</th>
                <th>Start date</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Topics == null || Model.Topics.Count == 0)
            {
                @Html.Raw("There is no topics here!")
            }
            else
            {
                foreach (Topic topic in Model.Topics)
                {
                    <tr>
                        <td>@topic.Posts.Count</td>
                        <td><a href="@Url.Action("GetTopic", new {id=topic.ObjectId})">@topic.Name</a></td>
                        <td>@topic.StartDate</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>