TwoWheelsWeb/ViewModels/ReviewViewModels.cs
using System.Collections.Generic;
using TwoWheelsWeb.Models.ReviewModels;

namespace TwoWheelsWeb.ViewModels
{
    public class ReviewViewModels
    {
        public class ObjectsToReviewViewModel
        {
            public List<ObjectToReview> Objects { get; set; }
        }

        public class ObjectToReview
        {
            public string ObjectId { get; set; }
            public string Mark { get; set; }
            public string Model { get; set; }
            public GearCategory GearCategory { get; set; }
        }

        public class CreateGearViewModel
        {
            public Gear Gear { get; set; }
            public List<GearCategory> GearCategories { get; set; }
        }

        public class ReviewMainViewModel
        {
            public List<ReviewMain> Reviews { get; set; }
        }

        public class ReviewMain
        {
            public string Mark { get; set; }
            public string Model { get; set; }
            public string ObjectId { get; set; }
            public Review Review { get; set; }
        }

        public class CreateReviewViewModel
        {
            public Review Review { get; set; }
            public string ObjectId { get; set; }
            public string Name { get; set; }
        }

        public class ObjectReviewsViewModel
        {
            public float Average { get; set; }
            public List<Review> Reviews { get; set; }
            public string ObjectId { get; set; }
            public string Name { get; set; }
        }
    }
}

TwoWheelsWeb/Controllers/ReviewController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using TwoWheelsWeb.Models.ReviewModels;
using TwoWheelsWeb.Services;
using static TwoWheelsWeb.ViewModels.ReviewViewModels;

namespace TwoWheelsWeb.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ReviewService _reviewService;

        public ReviewController()
        {
            this._reviewService = new ReviewService();
        }

        [HttpGet]
        public async Task<ActionResult> GetObjectsToReview()
        {
            var result = await _reviewService.GetObjectsToReview();

            return PartialView(result);
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var model = await _reviewService.GetModelForIndexPage();

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> CreateGear(string id)
        {
            return this.View(await _reviewService.GetCreateGearViewModel());
        }

        [HttpPost]
        public async Task<ActionResult> CreateGear(CreateGearViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var response = await _reviewService.CreateGear(model);

            return response ? RedirectToAction("GetObjectsToReview") : RedirectToAction("CreateGear");
        }

        [HttpGet]
        public ActionResult CreateGearCategory()
        {
            return PartialView(new GearCategory());
        }

        [HttpPost]
        public async Task<ActionResult> CreateGearCategory(GearCategory model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }

            var response = await _reviewService.CreateGearCategory(model);

            return response ? RedirectToAction("GetObjectsToReview") : RedirectToAction("CreateGearCategory");
        }

        [HttpGet]
        public ActionResult CreateReview(string id)
        {
            return this.PartialView(_reviewService.GetCreateReviewViewModel(id));
        }

        [HttpPost]
        public async Task<ActionResult> CreateReview(CreateReviewViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var response = await _reviewService.CreateReview(model);

            return response ? RedirectToAction("GetReviews", new { id = model.ObjectId}) : RedirectToAction("CreateReview");
        }

        [HttpGet]
        public async Task<ActionResult> GetReviews(string id)
        {
            var reviews = await _reviewService.GetReviewsForObject(id);

            return View(reviews);
        }
    }
}

TwoWheelsWeb/Views/Review/CreateGear.cshtml
@model TwoWheelsWeb.ViewModels.ReviewViewModels.CreateGearViewModel

@{
    Page.Title = "Add new gear element";
}

<div>
    <h3>Add new gear element</h3>
    <hr/>
    <br/>
    <div>
        @using (Html.BeginForm("CreateGear", "Review", FormMethod.Post))
        {
            <div class="grid">
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Gear.Mark)</div>
                    <div class="cell">@Html.EditorFor(x => x.Gear.Mark)</div>
                </div>
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Gear.Model)</div>
                    <div class="cell">@Html.EditorFor(x => x.Gear.Model)</div>
                </div>
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Gear.GearCategory)</div>
                    <div class="cell">@Html.DropDownListFor(x => x.Gear.GearCategory, new SelectList(Model.GearCategories.Select(x => x.Category), Model.Gear.GearCategory), "--please select--")</div>
                </div>
            </div>
            <button class="button btn-warning">Create!</button>
        }
    </div>
</div>

TwoWheelsWeb/Views/Review/CreateGearCategory.cshtml
@model TwoWheelsWeb.Models.ReviewModels.GearCategory

@{
    Page.Title = "Add new gear category";
}


<div>
    <h3>Create new gear category</h3>
    <hr />
    <br />
    <div>
        @using (Html.BeginForm("CreateGearCategory", "Review", FormMethod.Post))
        {
            <div class="grid">
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Category)</div>
                    <div class="cell">@Html.EditorFor(x => x.Category)</div>
                </div>
            </div>
            <button class="button btn-warning">Create!</button>
        }
    </div>
</div>

TwoWheelsWeb/Views/Review/CreateReview.cshtml
@model TwoWheelsWeb.ViewModels.ReviewViewModels.CreateReviewViewModel

<div>
    <h3>Add new review for @Model.ObjectId</h3>
    <hr />
    <br />
    <div>
        @using (Html.BeginForm("CreateReview", "Review", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.ObjectId)

            <div class="grid">
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Review.Stars)</div>
                    <div class="cell">@Html.EditorFor(x => x.Review.Stars)</div>
                </div>
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Review.Content)</div>
                    <div class="cell">@Html.EditorFor(x => x.Review.Content)</div>
                </div>
            </div>

            <button type="submit" class="button btn-warning">Create!</button>
        }
    </div>
</div>

TwoWheelsWeb/Views/Review/GetObjectsToReview.cshtml
@model TwoWheelsWeb.ViewModels.ReviewViewModels.ObjectsToReviewViewModel

@{
    Page.Title = "Objects to review";
}

<div>
    <table class="table">
        <thead>
        <tr>
            <th>Model</th>
            <th>Mark</th>
            <th>Category</th>
        </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Objects.Count; i++)
            {
                <tr onclick="@Url.Action("GetReviews", new {id = @Model.Objects[i].ObjectId })">
                    <td>@Model.Objects[i].Model</td>
                    <td>@Model.Objects[i].Mark</td>
                    <td>@Model.Objects[i].GearCategory</td>
                </tr>
            }
        </tbody>
    </table>
</div>

TwoWheelsWeb/Views/Review/GetReviews.cshtml
@using TwoWheelsWeb.ViewModels
@model ReviewViewModels.ObjectReviewsViewModel

@{
    Page.Title = "Reviews";
}

<h3>Reviews</h3>
<br/>
<hr/>
<br/>
@Html.Partial("CreateReview", new ReviewViewModels.CreateReviewViewModel {ObjectId = Model.ObjectId});

<br/>
<hr/>
<div class="grid">
    <div class="row cells2">
        <div class="cell">@Html.LabelFor(x => x.Average)</div>
        <div class="cell">@Model.Average</div>
    </div>
    @if (Model.Reviews == null || Model.Reviews.Count == 0)
    {
        @Html.Raw("There is no reviews")
    }
    else
    {
        for (int i = 0; i < Model.Reviews.Count; i++)
         {
             <div class="row cells2">
                 <div class="cell">@Html.LabelFor(x => x.Reviews[i].Stars)</div>
                 <div class="cell">@Model.Reviews[i].Stars</div>
             </div>
             <div class="row cells2">
                 <div class="cell">@Html.LabelFor(x => x.Reviews[i].Date)</div>
                 <div class="cell">@Model.Reviews[i].Date</div>
             </div>
             <div class="row cells2">
                 <div class="cell">@Html.LabelFor(x => x.Reviews[i].Content)</div>
                 <div class="cell">@Model.Reviews[i].Content</div>
             </div>
         }
    }
</div>

TwoWheelsWeb/Views/Review/Index.cshtml
@model TwoWheelsWeb.ViewModels.ReviewViewModels.ReviewMainViewModel
@{
    Page.Title = "Reviews";
}

<h3>Review Module</h3>
<br/>
<hr/>
<a href="@Url.Action("GetObjectsToReview")" class="button btn-warning">Objects to review</a>
<a onclick="createGearCategory()" class="button btn-warning">Create gear category</a>
<a onclick="createGear()"></a>
<br/>
<h4>Reviews from the last week</h4>
<div>
    @if (Model.Reviews == null || Model.Reviews.Count == 0)
    {
        @Html.Raw("There is no reviews")
    }
    else
    {
        for (int i = 0; i < Model.Reviews.Count; i++)
        {
            <div class="grid">
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Reviews[i].Mark)</div>
                    <div class="cell">@Model.Reviews[i].Mark</div>
                </div>
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Reviews[i].Model)</div>
                    <div class="cell">@Model.Reviews[i].Model</div>
                </div>
                <div class="row cells2">
                    <div class="cell">@Html.LabelFor(x => x.Reviews[i].Review)</div>
                    <div class="cell">@Model.Reviews[i].Review</div>
                </div>
            </div>

        }
    }
</div>

<div id="gearCategoryDialog" class="dialog" data-role="dialog" data-overlay="true" data-close-button="true" data-type="warning">
</div>

@section scripts{
    <script type="text/javascript">
        function createGearCategory() {
            $.ajax({
                type: "GET",
                url: "/Review/CreateGearCategory",
                datatype: "html",
                success: function(data) {
                    $('#gearCategoryDialog').html(data);
                    metroDialog.open('#gearCategoryDialog');
                },
                error: function() {
                    alert("Something gone wrong");
                }
            });
        }
    </script>
}